### ISSUE TITLE
Improve loading performance for letter images+data

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/scriptchart-backend#23]
The scriptchart contents currently load slowly if several manuscripts and letters are selected. There are a few main causes:

1. Processing bottlenecks: requests for the "untrimmed" (non-binarized) images actually require the Django server to crop the corresponding manuscript page images via the PIL library every time a letter location is requested; the server can become quite sluggish when several of these requests pile up.
2. Network bottlenecks: throughput of image data from the Reclaim server seems to be another culprit; the binarized images usually load quickly, but the trimmed images, even after being generated, seem to download slowly due to their comparatively larger size.
3. (Less problematic, but not ideal): The JSON API calls that are necessary to query all of the letter coordinates for all of the pages of a given manuscript can multiply quickly, due in part to how the DB tables and Django views are set up.

Potential solutions:
1. (Less desirable): Enable caching for most requests to the Django back-end. This is easy to enable, but introduces possible pain points around cache configuration, and doesn't really solve the underlying issues re: repetitive image cropping and sub-optimal DB table configuration.
2. (Preferred): Pre-generate the cropped images for all 4 contextual margin size options, modify the API so that these can be requested from the front-end and more or less treated like normal image requests. Storage impact should be minimal, though we also should consider placing the images into a CDN-enabled hosting solution (Amazon S3?) to reduce network and distance bottlenecks. Generation of cropped images should be integrated into deployment of the site, and/or updates to the DB (former is easier to manage).
3. (Less important, but would be nice): refactor/denormalize the DB and Django views setup so that coordinates lookup involves fewer API queries, and the results can be sent to the front-end as a batch rather than one at a time.

The solution likely also will affect the front-end to some degree, if the API methods for querying coordinates data and images have to change.

**Comment by simonwiles** [comment]
The bulk of this work (enough to close the issue) was completed a long time ago.  There are still some improvements that could be made, for sure, but (2) and (3) above have been implemented.
