### ISSUE TITLE
Ensure that contextual letter images are wider than they are tall

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/scriptchart-backend#28]
The consensus is that the letter + context image should have approximate letterbox (16x9) dimensions, or at least they should not be any "skinnier" than this. This is already implemented on the client side (see [this branch](https://github.com/sul-cidr/scriptchart/tree/feature/popup-aspect-ratio)), but will need to be re-implemented on the server side (with API modifications, most likely) in order to pre-generate letter images to improve loading performance (see https://github.com/sul-cidr/scriptchart-backend/issues/23).

**Comment by simonwiles** [comment]
Superseded by pre-generated letter-in-context images.
